name: CI-CD
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Composer cache dir
                run: echo "$(composer config --global cache-files-dir)"




