name: First workflow
on: push

jobs:
    First-job:
        runs-on: ubuntu-latest
        steps:
            - name: Show github
              run: echo '${{ toJSON(github) }}'
            - run: echo '${{ toJSON(secrets) }}'
            - run: echo '${{ toJSON(vars) }}'
            - run: echo '${{ toJSON(env) }}'

