name: First workflow
on: push

jobs:
    First-job:
        runs-on: ubuntu-latest
        steps:
            - run: ${{ toJSON(github) }}
            - run: ${{ toJSON(secrets) }}
            - run: ${{ toJSON(vars) }}
            - run: ${{ toJSON(env) }}

